#+title: ox-zenn.el
#+author: Naoya Yamashita

[[https://github.com/conao3/ox-zenn.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/ox-zenn.el.png]]

[[https://github.com/conao3/ox-zenn.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/ox-zenn.el.svg?style=flat-square]]
[[https://github.com/conao3/ox-zenn.el/releases][https://img.shields.io/github/tag/conao3/ox-zenn.el.svg?style=flat-square]]
[[https://github.com/conao3/ox-zenn.el/actions][https://github.com/conao3/ox-zenn.el/workflows/Main%20workflow/badge.svg]]

Zenn-flavored Markdown export backend for Org mode.

* Overview

ox-zenn provides an Org mode export backend for [[https://zenn.dev/][Zenn]], a popular Japanese tech article platform. Write your articles in Org mode and export them directly to Zenn-compatible Markdown format.

[[https://github.com/conao3/ox-zenn.el][https://raw.githubusercontent.com/conao3/files/master/blob/ox-zenn.el/ox-zenn.gif]]

** Features

- Full Zenn Markdown syntax support
- YAML frontmatter generation
- Code block language highlighting
- Table conversion
- Footnote support
- LaTeX fragment handling
- Image embedding with width specifications

* Requirements

- Emacs 27.1 or later
- Org mode 9.0 or later

* Installation

** From MELPA

#+begin_src emacs-lisp
(use-package ox-zenn
  :ensure t)
#+end_src

** With leaf.el

#+begin_src emacs-lisp
(leaf ox-zenn :ensure t)
#+end_src

** Manual Installation

Clone the repository and add it to your load path:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/ox-zenn.el")
(require 'ox-zenn)
#+end_src

* Usage

After loading ox-zenn, use the Org export dispatcher:

1. Open an Org file
2. Press =C-c C-e= to open the export dispatcher
3. Press =z= for Zenn Markdown options:
   - =Z= - Export to temporary buffer
   - =z= - Export to file
   - =o= - Export to file and open

You can also export programmatically:

#+begin_src emacs-lisp
(org-zenn-export-to-markdown)    ; Export to file
(org-zenn-export-as-markdown)    ; Export to buffer
#+end_src

* Configuration

** Headline Offset

When publishing to Zenn, =h1= is typically used for the article title. To offset your Org headings (so =*= becomes =##= instead of =#=), configure =org-zenn-headline-offset=:

#+begin_src emacs-lisp
;; Global setting
(setq org-zenn-headline-offset 1)
#+end_src

Or per-document:

#+begin_src org
#+options: headline-offset:1
#+end_src

** Last Modified Timestamp

ox-zenn inserts a =last_modified= frontmatter field by default. To disable this:

#+begin_src emacs-lisp
;; Global setting
(setq org-zenn-with-last-modified nil)
#+end_src

Or per-document:

#+begin_src org
#+options: last-modified:nil
#+end_src

* Known Limitations

** Column Groups in Tables

Tables using Org's [[https://orgmode.org/manual/Column-Groups.html][column groups]] feature are not fully supported. Column group markers may appear in the output.

#+begin_src org
  | Head | Head | Head      |
  |------+------+-----------|
  | Text | Text | Teeeeeext |
  | Text | Text | Text      |

  |   | Head | Head | Head      |
  |---+------+------+-----------|
  | / | <    | >    | <>        |
  |   | Text | Text | Teeeeeext |
  |   | Text | Text | Text      |
#+end_src

Transforms into:

#+begin_src markdown
  | Head | Head | Head      |
  | ---- | ---- | --------- |
  | Text | Text | Teeeeeext |
  | Text | Text | Text      |

  | Head | Head || Head |
  | --- | --- | --- |
  | Text | Text || Teeeeeext |
  | Text | Text || Text |
#+end_src

** Multiple Horizontal Rules in Tables

Tables with multiple horizontal separators (row groups) will have the extra separators stripped, preserving only the header separator.

#+begin_src org
  | Head | Head | Head      |
  |------+------+-----------|
  | Text | Text | Teeeeeext |
  | Text | Text | Text      |
  |------+------+-----------|
  | Text | Text | Text      |
  | Text | Text | Text      |
#+end_src

Transforms into:

#+begin_src markdown
  | Head | Head | Head      |
  | ---- | ---- | --------- |
  | Text | Text | Teeeeeext |
  | Text | Text | Text      |
  | Text | Text | Text      |
  | Text | Text | Text      |
#+end_src

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

** Development Setup

Install [[https://github.com/conao3/keg][keg]] for running tests:

#+begin_src shell
git clone https://github.com/conao3/keg ~/.keg
export PATH="$HOME/.keg/bin:$PATH"
#+end_src

** Workflow

#+begin_src shell
git checkout -b feature-branch
# Make your changes
make test
git commit -am "Description of changes"
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/ox-zenn.el/blob/master/LICENSE][LICENSE]] for details.

Copyright (C) Naoya Yamashita ([[https://github.com/conao3][conao3]])
